esphome:
  name: extractor

esp8266:
  board: sonoff_basic

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: !secret ip_extractor
    gateway: !secret gateway
    subnet: !secret subnet

  ap:
    ssid: "Extractor"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

text_sensor:
  - platform: version
    name: Extractor
  - platform: wifi_info
    ip_address:
      name: "IP Extractor"

sensor:
  - platform: uptime
    name: "Extractor Uptime"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Extractor Status"

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Boton Fisico"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Extractor"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
