esphome:
  name: llavero-inteligente

esp8266:
  board: d1_mini_lite

logger:

api:
  password: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: !secret ip_llavero-wemosd1
    gateway: !secret gateway
    subnet: !secret subnet

  ap:
    ssid: "llavero-inteligente"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# ////////////////////////////////////////////////////////////////////////
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP llavero WEMOS"

binary_sensor:
  - platform: gpio
    name: "Llaves Yaz"
    device_class: occupancy
    pin:
      number: D1
      inverted: true
      mode:
        input: true
        pullup: true

  - platform: gpio
    name: "Llaves Rey"
    device_class: occupancy
    pin:
      number: D2
      inverted: true
      mode:
        input: true
        pullup: true

  - platform: gpio
    name: "Llaves JOY"
    device_class: occupancy
    pin:
      number: D3
      inverted: true
      mode:
        input: true
        pullup: true

  - platform: gpio
    name: "Llaves CASA"
    device_class: occupancy
    pin:
      number: D4
      inverted: true
      mode:
        input: true
        pullup: true

  - platform: status
    name: "Llavero Inteligente"
