esphome:
  name: tomas-pc

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: !secret ip_tomas_pc
    gateway: !secret gateway
    subnet: !secret subnet

  ap:
    ssid: "Tomas Pc"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

text_sensor:
  - platform: version
    name: Tomas Pc Version
  - platform: wifi_info
    ip_address:
      name: "IP Tomas Pc"

sensor:
  - platform: uptime
    name: "Tomas PC Uptime"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Boton Fisico"
    on_press:
      - switch.toggle: relay
      - switch.toggle: relay2

switch:
  - platform: gpio
    name: "Monitor 2"
    pin: GPIO12
    id: relay
  - platform: gpio
    name: "Monitor 1"
    pin: GPIO05
    id: relay2

status_led:
  pin:
    number: GPIO13
    inverted: yes
