esphome:
  name: ventilador-juegos
  platform: ESP8266
  board: esp01_1m

logger:

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: !secret ip_ventilador_juegos
    gateway: !secret gateway
    subnet: !secret subnet

  ap:
    ssid: "Ventilador-Juegos"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# ////////////////////////////////////////////////////////////////////////

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO03
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Ventilador Juegos"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "Ventilador Juegos"

switch:
  - platform: gpio
    name: "Ventilador Juegos"
    pin: GPIO12
    id: relay

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP ESP VentiladorJuegos"

















